vich_uploader: 
  db_driver: orm

  mappings: 
    blog_image:
      uri_prefix: '%app.path.blog_image%'
      upload_destination: '%kernel.project_dir%/public/imagenes/blogs'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true